Repository coder2hacker/Explore-open-source, pull requests merged in 2022-09, with the labels that each got.

#71 new javascript concept
  accidental-global.js
  class-multiple-constructors.js
  eventloop-order.js
  floatingpoint-problem.js
  function-arrow-context.js
  function-context.js
  function-expression.js
  function-hoisted.js
  function-without-new.js
  functiontest.js
  semicolon-issue.js
Labels: hacktoberfest2022

#73 Tower of Hanoi using C
  TOWER.CPP
Labels: good first issue, hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022, FIRST-MR

#74 C program using Recursion
  MUL.CPP
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022, FIRST-PR, FIRST-MR

#75 Hashing program using C
  doublehash.C
Labels: good first issue, hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022, FIRST-PR, FIRST-MR

#76 sql query for data science
  Exercise Files/01_01.sql
  Exercise Files/01_02.sql
  Exercise Files/01_03.sql
  Exercise Files/01_04.sql
  Exercise Files/01_05.sql
  Exercise Files/01_06.sql
  Exercise Files/01_07.sql
  Exercise Files/01_08.sql
  Exercise Files/01_09.sql
  Exercise Files/01_10.sql
  Exercise Files/01_11.sql
  Exercise Files/01_12.sql
  Exercise Files/02_01.sql
  Exercise Files/03_01.sql
  Exercise Files/04_01.sql
  Exercise Files/05_01.sql
  Exercise Files/06_01.sql
  Exercise Files/07_01.sql
  Exercise Files/08_01.sql
  Exercise Files/09_01.sql
  Exercise Files/10_01.sql
  Exercise Files/11_01.sql
  Exercise Files/12_01.sql
Labels: good first issue, hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022, FIRST-PR, FIRST-MR

#78 Linearprobing using C
  Linearprobing.C
Labels: good first issue, hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022, FIRST-MR
