Repository coder2hacker/Explore-open-source, pull requests merged in 2022-10, with the labels that each got.

#80 Adding ROCK_PAPER_SCISSORS.py file which is a simple game written in python.
  ROCK_PAPER_SCISSORS.py
  d-coder111.json
Labels: good first issue, hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022, FIRST-MR

#85 Add files via upload
  learnaws/bash_script.sh
  learnaws/script.js
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#87 Create RatInAMaze.java program
  RatInAMaze.java
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#86 Create minimum_path_sum.py
  minimum_path_sum.py
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#88 Disk Space Analysis
  Disk Space Analysis.cpp
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#120 Rainwater Problem
  07 rainwater-trap.cpp
  ChatBot.py
  CreditRisk.py
  Detect Capital
  HindiDataCleaning.py
  SnakeGame.py
  array_rotation.cpp
  godsakani.json
  java program/Heap_sort.java
  java program/Hill_cipher.java
  java program/KMP.java
  java program/ReverseArray.java
  python program/Caesar_cipher.py
  simplify_path.cpp
  superArrayOfObjects.js
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#119 Stack
  07 check_subset.cpp
  07 rainwater-trap.cpp
  simplify_path.cpp
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#121 Subset
  07 check_subset.cpp
  07 rainwater-trap.cpp
  ChatBot.py
  CreditRisk.py
  Detect Capital
  HindiDataCleaning.py
  SnakeGame.py
  array_rotation.cpp
  godsakani.json
  java program/Heap_sort.java
  java program/Hill_cipher.java
  java program/KMP.java
  java program/ReverseArray.java
  python program/Caesar_cipher.py
  simplify_path.cpp
  superArrayOfObjects.js
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#118 Create Longest Common Prefix
  Longest Common Prefix
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#115 Create Find First and Last Position of Element in Sorted Array Given …
  Find First and Last Position of Element in Sorted Array Given an array of integers nums sorted in non-decreasing order, find the starting and ending position of a given target value.
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#117 Create Ransom Note
  Ransom Note
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#122 Trie DS
  07 check_subset.cpp
  07 rainwater-trap.cpp
  ChatBot.py
  CreditRisk.py
  Detect Capital
  HindiDataCleaning.py
  SnakeGame.py
  array_rotation.cpp
  godsakani.json
  java program/Heap_sort.java
  java program/Hill_cipher.java
  java program/KMP.java
  java program/ReverseArray.java
  little_cute_cat_trie.cpp
  python program/Caesar_cipher.py
  simplify_path.cpp
  superArrayOfObjects.js
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#116 Create Mirror Reflection
  Mirror Reflection
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#128 Create Reverse_Linked_list.java
  java program/Reverse_Linked_list.java
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#127 Created pancake-sorting.cpp
  pancake-sorting.cpp
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#126 Added Graph Plotter
  python program/ploter.py
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#131 Deque Using C
  DEQU.CPP
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#130 Amazon
  Amazon - LeetCode.pdf
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#132 Arduino Project
  project_3.ino
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#133 Arduino Uno
  project_4.ino
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#138 Create create a telegram bot using Python
  create a telegram bot using Python
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#137 Create Password Generator using Python
  Password Generator using Python
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#136 Create Method Parameters in C#
  Method Parameters in C#
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#135 Create devBlog1
  devBlog1
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#134 Create BlindDSASheet
  BlindDSASheet
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#143 Add files via upload
  SQLQuery1.sql
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#142 Create SMART in Scrum
  SMART in Scrum
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#144 Add files via upload
  SQLQuery2.sql
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#141 Create awesomeJS
  awesomeJS
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#140 Add files via upload
  Goldman Sachs - LeetCode alltime.pdf
  Google - LeetCode.pdf
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#145 Add files via upload
  SQLQuery3.sql
  SQLQueryEmp.sql
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#139 Create Himanshu.json
  Himanshu.json
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#146 Add files via upload
  OOP.txt
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#147 Add files via upload
  Design Patterns Notes.docx
  meganzhack.pdf
  timer 18 aug.txt
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#148 Add files via upload
  awesomeJAVA
  jQuery.3.4.1.nupkg
  js basics.txt
  repo.txt
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#152 Create Selection_Sort.java
  java program/Selection_Sort.java
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#151 Create Merge_Sort.java
  java program/Merge_Sort.java
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#150 Adds introductory JSON file
  toadwx.json
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#154 Create Quick_Sort.py
  python program/Quick_Sort.py
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#149 Create Fibonacci_Recursive.java
  java program/Fibonacci_Recursive.java
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#155 Create 2_Stacks_in_Array.py
  python program/2_Stacks_in_Array.py
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#156 Added Files By Uploads
  Quick Select Algorithm in C++.cpp
  breadth-first-search.cpp
  floyds_cycle_detection.cpp
  kmp.cpp
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#157 Add json
  harshit.json
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#158 Add files via upload
  Tutorial_EDIT.pdf
  cpp_tutorial.pdf
  cprogramming_tutorial.pdf
  vb.net notes
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#159 Bubble Sort using Java.
  BubbleSort1.java
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#160 Command Line Argument using Java.
  Command_Line_Argument.java
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#161 Ragged Array using Java.
  Ragged_Array.java
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#162 Exception Handling using Java.
  Exception1.java
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#163 2D Array using Java
  Array_2D.java
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#164 Created Convert OctalToDecimal.java
  java program/OctalToDecimal.java
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#165 Added Linked List palindrome detection program in Java
  CaptIndhuja.json
  java program/PalindromeLL.java
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#166 Create Selection sort_Adarsh_Mohanty
  python program/Selection sort_Adarsh_Mohanty
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#167 Add files via upload
  Anmol's Resume.pdf
  Screenshot (942).png
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#168 Create Random_Password_Generator.py
  python program/Random_Password_Generator.py
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#169 Create AdityaMandage.json
  AdityaMandage.json
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#172 Add files via upload
  New Text Document (2).txt
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#174 a cpp program
  Longest_mountain_inArray_Leetcde_cpp.txt
  candy_problem_leetcode_cpp.txt
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#178 ShortestUnsortedContinuosSubarray_leetcode_cpp
  ShortestUnsortedContinuosSubarray_leetcode_cpp.txt
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#177 Add files via upload
  mile_to_km_coverter.py
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#176 Add files via upload
  ascii.c
  countvowel.c
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#175 Add files via upload
  Notice elective updation for AI DS and AI ML.docx
  hdb.txt
  kashbksf.txt
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#179 Add files via upload
  ONLINE SHOPPING CART (E-COMMERCE WEBSITE).docx
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#180 Minecraft Game Python Project
  Minecraft-in-Python-main/Minecraft-in-Python-main/UrsaCraft_video.py
  Minecraft-in-Python-main/Minecraft-in-Python-main/assets/Grass_block.blend
  Minecraft-in-Python-main/Minecraft-in-Python-main/assets/Sans.png
  Minecraft-in-Python-main/Minecraft-in-Python-main/assets/arm.blend
  Minecraft-in-Python-main/Minecraft-in-Python-main/assets/arm.blend1
  Minecraft-in-Python-main/Minecraft-in-Python-main/assets/arm.mtl
  Minecraft-in-Python-main/Minecraft-in-Python-main/assets/arm.obj
  Minecraft-in-Python-main/Minecraft-in-Python-main/assets/arm_texture.png
  Minecraft-in-Python-main/Minecraft-in-Python-main/assets/arm_texture.psd
  Minecraft-in-Python-main/Minecraft-in-Python-main/assets/block.mtl
  Minecraft-in-Python-main/Minecraft-in-Python-main/assets/block.obj
  Minecraft-in-Python-main/Minecraft-in-Python-main/assets/block_textures.psd
  Minecraft-in-Python-main/Minecraft-in-Python-main/assets/brick_block.png
  Minecraft-in-Python-main/Minecraft-in-Python-main/assets/dirt_block.png
  Minecraft-in-Python-main/Minecraft-in-Python-main/assets/grass_block.png
  Minecraft-in-Python-main/Minecraft-in-Python-main/assets/punch.xmp
  Minecraft-in-Python-main/Minecraft-in-Python-main/assets/punch_sound.wav
  Minecraft-in-Python-main/Minecraft-in-Python-main/assets/skybox.png
  Minecraft-in-Python-main/Minecraft-in-Python-main/assets/stone_block.png
  Minecraft-in-Python-main/Minecraft-in-Python-main/ursina_intro.py
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#181 Product_array_Except_self
  Product_array_Except_self.txt
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#182 Create GuessTheNumber.java
  GuessTheNumber.java
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#185 Add files via upload
  Fibonacci_heap.cpp
  van-emde-boas-tree.cpp
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#187 Add file By Uploads
  SplayTree.cpp
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#186 Add File with Uploads
  Dart Cheet Sheet.txt
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#190 Light on off using html css and js
  LightOn and off.html
  click.mp3
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#189 turtle race
  python program/turtle race.py
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#188 Magic grid game in Python from scratch
  python program/Magic Grid.py
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#191 Distortion using html css
  Distortion of SIT.html
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#193 checkbox using html and css
  checkbox.html
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#192 CompatibiltyTest.js
  compatibiltyTest.js
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#194 Text input design using HTML and CSS
  text input design.html
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#195 Instagram symbol using HTML and CSS
  instagram.html
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#198 Added Html in to-do list
  JS Projects/To Do/index.html
  JS Projects/To Do/style.css
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#196 Add files via upload
  CountedB-Trees.cpp
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#199 Chrome Extension
  manifest.json
  popup.html
  popup.js
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#201 Html
  index11.html
  style11.css
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#202 Styling
  index14.html
  style14.css
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#206 Janmansh and coins using C++
  janmansh_and_coins.cpp
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#207 battery Low using c++
  battery_low.cpp
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#203 Added new json file as per contributing sample
  ChadGichuki.json
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#205 Add files via upload
  employee.c
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#208 Create script.js in todo list
  JS Projects/To Do/script.js
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#209 Updated code
  atm.cpp
  cyclic_quadrilateral.cpp
  move_all_negative_elements_to_end.cpp
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#210 Kth smallest element using cpp
  kth_smallest_element.cpp
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#211 Alphabet pattern
  alphabetpattern.c
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#212 Added Code to compute pairs having a given sum
  Dvd1234.java
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#216 Add files via upload
  Number_Guessing_Game.py
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#215 Add files via upload
  HeapSort.cpp
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#214 Create Turtle.py
  python program/Turtle.py
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#218 Added Form
  BST.cpp
  Project_1.html
  cssProject.css
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#217 Add files via upload
  Floyd Warshall Algorithm in C++.cpp
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#223 added code for interval prime numbers
  intervalPrimenumbers.py
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#221 bubble sort code in java
  java program/Bubble_sort.java
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#220 binary search in java
  java program/binary_search.java
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#219 Shell Sort Code in Java
  java program/shell_sort.java
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#224 Added my file ie himanshu1221
  HimanshuChhatwal1221.json
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#227 GUI using Python
  DLL .c
  GUI.ipynb
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#226 added code for arm strong number
  Armstrongnumber.py
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#230 Circular Queue using C
  Cricular__Queue.c
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#236 Create Swap_without_3rd_variable
  java program/Swap_without_3rd_variable
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#235 Fibonacci Series
  python program/fibonaccifunction.py
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#234 Add files via upload
  VisualBasic_NETNotesForProfessionals.pdf
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#233 Update MUL.CPP
  MUL.CPP
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#232 Update Binary_to_Decimal.cpp
  Binary_to_Decimal.cpp
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#231 Create pattern.py
  pattern.py
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#237 Kruskals cpp code file added
  Kruskals.cpp
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#238 Login/SignUp landing page
  styleCss.css
  webpage.html
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#241 Create binary.py
  binary.py
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#242 Add files via upload
  Use Case Diagram.docx
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#245 Floyd_Warshall_Algorithm.cpp
  Floyd_Warshall_Algorithm.cpp
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#244 dijkstra cpp Code File Added
  dijkstra.cpp
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#243 Add files via upload
  INHERITENCE IN VB.NET latest (3).zip
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#249 Square Sum Array Using C
  Complex_No_Addition.cpp
  Count_Number_of_object.cpp
  Object_Function_Argument.cpp
  Square_Sum_Array.c
  Triangle.cpp
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#250 Inline Using CPP
  Friend_function_of_multiple_class1.cpp
  Inline.cpp
  Nested_Class.cpp
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#247 Speech.py
  Speech.py
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#246 Titanic.py
  Titanic.py
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#258 Create DuplicateWord.java
  DuplicateWord.java
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#257 Create ArraySumStream.java
  ArraySumStream.java
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#259 Create harsh.json
  harsh.json
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#256 Tower Of Hanoi using recursion
  clock.css
  clock.html
  towerOfHanoi.cpp
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#255 Added Parking lot system file
  ParkingLot-master/LowLevel_ParkingSystem.py
  ParkingLot-master/Parking_lot_Eeshan_Demo.pptx
  ParkingLot-master/Vehicle.py
  ParkingLot-master/__pycache__/Vehicle.cpython-310.pyc
  ParkingLot-master/run_test_case.txt
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#261 Js files
  JS Projects/apni_kaksha-02.html
  JS Projects/index.html
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#260 Added contributor in JSON file
  kumar.json
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#253 Calculator using cpp
  calculator.cpp
  factorial .cpp
  fibonnaci series.cpp
  linear search.cpp
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#262 Create Html file example
  Html file example
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#263 Create Calculate Standard Deviation using Function
  Calculate Standard Deviation using Function
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#264 Create Calculate Average of Numbers Using Arrays
  Calculate Average of Numbers Using Arrays
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#266 Create Compute Power Manually
  Compute Power Manually
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#267 Create Program checks if the number is positive or negative
  Program checks if the number is positive or negative
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#268 Create If the number is positive
  If the number is positive
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#269 Create Program to find the sum of all numbers stored in a list
  Program to find the sum of all numbers stored in a list
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#270 Create Program to iterate through a list using indexing
  Program to iterate through a list using indexing
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#265 Create Armstrong Number Program
  Armstrong Number Program
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#271 Create Python Program to Check Prime Number
  Python Program to Check Prime Number
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#272 Create This program adds two numbers
  This program adds two numbers
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#273 Create Factorial of a Number using Loop
  Factorial of a Number using Loop
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#274 Create Python Program to Calculate the Area of a Triangle
  Python Program to Calculate the Area of a Triangle
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#278 Binary Search
  BINARY.CPP
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#275 Added Code for Automorphic Number
  automorphic_number.cpp
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#279 Add file By uploads
  binary-space-partitioning.cpp
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#290 kadane's algorithm
  kadane's algorithm
Labels: HACKTOBERFEST-ACCEPTED

#289 Add files via upload
  index.html
  index.js
  var x=52, y=10;.js
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#288 Calculator
  cal.html
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#292 Added Two Sum Problem
  twosum.cpp
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#293 adding affine chiper
  python program/affine_chiper.py
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#294 usinglink
  usinglink.cpp
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022
